# routes.py

MDCLRoute = [
    "Burton          1",
    "Tutnury         1",
    "Burton          2",
    "Edge Hill       2",
    "Swadlincote     4",
    "Burton          4",
    "Burton          6",
    "Eton Park       6",
    "Queens Hospital 8",
    "Swadlincote     8",
    "EM Airport      9",
    "Burton          9",
    "Acorn Inn       10",
    "Burton          10",
    "Acorn Inn       10S",
    "JTFS            10S",
    "Burton          11",
    "Anglesey Road   11",
    "Burton          12",
    "Lichfeild       12",
    "Burton          12E",
    "Lichfeild       12E",
    "Burton          X12",
    "Lichfield       X12",
    "Stretton        17",
    "Burton          17",
    "Burton          18",
    "Dalebrook       18",
    "Burton          19",
    "Ashby           19",
    "Burton          19A",
    "Mercia Park     19A",
    "Burton          19C",
    "Moira           19C",
    "Fazeley         20",
    "Tamworth        20",
    "Mercia Park     20",
    "Swadlincote     21",
    "Burton          21",
    "Burton          21E",
    "Linton          21E",
    "Burton          22",
    "Swadlincote     22",
    "Lower Midway    24",
    "Swadlincote     24",
    "Lichfeild Curle 31",
    "Lichfeild Curle 32",
    "Willingtion     70",
    "Derby           70",
    "Derby           70A",
    "Castle Donington125",
    "Leicster        125",
    "Ashby           129",
    "Loughborough    129",
    "Repton          213",
    "Bretby          213",
    "Burton          401",
    "Uttoxeter       401",
    "Burton          402",
    "Uttoxeter       402",
    "Burton          402A",
    "Uttoxeter       402A",
    "Burton          403",
    "Uttoxeter       403",
    "Queens Hospital 801",
    "Edge Hill       801",
    "Fauld           802",
    "De Ferrers      802",
    "Alrewas         805",
    "John Taylor High805",
    "Alrewas         806",
    "John Taylor High806",
    "Beam Hill       807",
    "John Taylor High807",
    "Yoxall          808",
    "John Taylor High808",
    "Shobnall        809",
    "John Taylor High809",
    "Shobnall        810",
    "John Taylor High810",
    "Shobnall        811",
    "John Taylor High811",
    "Alrewas         811",
    "John Taylor High812",
    "Burton          812",
    "Friary School   817",
    "Fradley         817",
    "Friary School   818",
    "Fradley         818",
    "Lichfeild       819",
    "Hill Ridware    819",
    "Pingle School   821",
    "Burton          821",
    "Pingle School   822",
    "Rosliston       822",
    "Will Allitt Sch 825",
    "Netherseal      825",
    "Will Allitt Sch 826",
    "Church Gresley  826",
    "Paget School    827",
    "Horninglow      827",
    "Hill Ridware    829",
    "Lichfeild       829",
    "Hilton          831",
    "John Taylor Free831"
]

JWOMRoute = [
    "Not In Service  000",
    "Mainstone       1",
    "Birtchwood Hts  1",
    "Mainstone       2",
    "Oakwood Grove   2",
    "Super Loop CW   3",
    "Super Loop ACW  3",
    "Mainstone       301",
    "Cedar Ridge     301",
    "Mainstone       302",
    "Cedar Ridge     302",
    "Fairhaven       303",
    "Cedar Ridge     303",
    "Springvale      304",
    "Cedar Ridge     304",
    "Mainstone       401",
    "Springvale      401",
    "Cedar Ridge     402",
    "Springvale      402",
    "Willowbrook     403",
    "Springvale      403",
    "Mainstone       501",
    "Fairhaven       501",
    "Mainstone       502",
    "Fairhaven       502",
    "Cedar Ridge     503",
    "Fairhaven       503",
    "Willowbrook     504",
    "Fairhaven       504",
    "Mainstone       601",
    "Willowbrook     601",
    "Mainstone       602",
    "Willowbrook     602",
    "Fairhaven       603",
    "Willowbrook     603",
    "Springvale      604",
    "Willowbrook     604",
    "The Villager    V1",
    "The Villager    V2",
    "The Villager    V3",
    "Mainstone       X3",
    "Cedar Ridge     X3",
    "Mainstone       X4",
    "Springvale      X4",
    "Mainstone       X5",
    "Fairhaven       X5",
    "Mainstone       X6",
    "Willowbrook     X6",
    "Cedar Ridge     A3",
    "Springvale      A4",
    "Fairhaven       A5",
    "Willowbrook     A6"
]

arrays = {
    "JWOM": JWOMRoute,
    "MDCL": MDCLRoute,
}

Companys = ["JWOM", "MDCL"]
